#include "minunit.h"

#include "get_quat_from_K.h"
#include "get_quat_from_K_initialize.h"
#include "get_quat_from_K_terminate.h"
#include "optimal_request.h"
#include "optimal_request_init.h"

// This is generated by {root_dir}/matlab/tests/gen_meas_for_c.m
#include "test_meas_data.h"	

#include "helper.h"

void test_setup(void) {
	get_quat_from_K_initialize();
}

void test_teardown(void) {
	get_quat_from_K_terminate();
}

MU_TEST(test_compare_matlab_and_c) {
	float q_est[4];
	float euler_est[3], euler_gt[3];
	float rms_errors[TEST_MEAS_DATA_MEAS_LEN];
	struct0_T or_handle;

	// these values are not changing
	or_handle.Mu_noise_var = TEST_MEAS_DATA_MU_NOISE_VAR;
	or_handle.Eta_noise_var = TEST_MEAS_DATA_ETA_NOISE_VAR;
	or_handle.dT = TEST_MEAS_DATA_DT;

	// first measurements
	or_handle.r[0] = test_meas_data_ref_acc[0][0];
	or_handle.r[1] = test_meas_data_ref_acc[0][1];
	or_handle.r[2] = test_meas_data_ref_acc[0][2];
	or_handle.r[3] = test_meas_data_ref_mag[0][0];
	or_handle.r[4] = test_meas_data_ref_mag[0][1];
	or_handle.r[5] = test_meas_data_ref_mag[0][2];

	or_handle.b[0] = test_meas_data_bdy_acc[0][0];
	or_handle.b[1] = test_meas_data_bdy_acc[0][1];
	or_handle.b[2] = test_meas_data_bdy_acc[0][2];
	or_handle.b[3] = test_meas_data_bdy_mag[0][0];
	or_handle.b[4] = test_meas_data_bdy_mag[0][1];
	or_handle.b[5] = test_meas_data_bdy_mag[0][2];

	or_handle.w[0] = test_meas_data_bdy_gyr[0][0];
	or_handle.w[1] = test_meas_data_bdy_gyr[0][1];
	or_handle.w[2] = test_meas_data_bdy_gyr[0][2];

	// init optimal_req on 1st meas
	optimal_request_init(&or_handle);

	// get q from K
	get_quat_from_K(or_handle.K, q_est);
	// convert q to Eulers
	get_euler_from_q(euler_est, q_est);

	// convert rad to deg
	euler_est[0] = RAD2DEG(euler_est[0]);
	euler_est[1] = RAD2DEG(euler_est[1]);
	euler_est[2] = RAD2DEG(euler_est[2]);

	euler_gt[0] = RAD2DEG(test_meas_data_euler_gt[0][0]);
	euler_gt[1] = RAD2DEG(test_meas_data_euler_gt[0][1]);
	euler_gt[2] = RAD2DEG(test_meas_data_euler_gt[0][2]);

	// calculate rms error
	rms_errors[0] = euler_rms_error(euler_est, euler_gt);

	for (int i=1; i<TEST_MEAS_DATA_MEAS_LEN; i++) {
		// fill r and b vectors with measurements
		or_handle.r[0] = test_meas_data_ref_acc[i][0];
		or_handle.r[1] = test_meas_data_ref_acc[i][1];
		or_handle.r[2] = test_meas_data_ref_acc[i][2];
		or_handle.r[3] = test_meas_data_ref_mag[i][0];
		or_handle.r[4] = test_meas_data_ref_mag[i][1];
		or_handle.r[5] = test_meas_data_ref_mag[i][2];

		or_handle.b[0] = test_meas_data_bdy_acc[i][0];
		or_handle.b[1] = test_meas_data_bdy_acc[i][1];
		or_handle.b[2] = test_meas_data_bdy_acc[i][2];
		or_handle.b[3] = test_meas_data_bdy_mag[i][0];
		or_handle.b[4] = test_meas_data_bdy_mag[i][1];
		or_handle.b[5] = test_meas_data_bdy_mag[i][2];

		or_handle.w[0] = test_meas_data_bdy_gyr[i][0];
		or_handle.w[1] = test_meas_data_bdy_gyr[i][1];
		or_handle.w[2] = test_meas_data_bdy_gyr[i][2];

		// call optimal req on meas
		optimal_request(&or_handle);

		// get q from K
		get_quat_from_K(or_handle.K, q_est);

		// convert q to Eulers
		get_euler_from_q(euler_est, q_est);

		// convert rad to deg
		euler_est[0] = RAD2DEG(euler_est[0]);
		euler_est[1] = RAD2DEG(euler_est[1]);
		euler_est[2] = RAD2DEG(euler_est[2]);

		euler_gt[0] = RAD2DEG(test_meas_data_euler_gt[i][0]);
		euler_gt[1] = RAD2DEG(test_meas_data_euler_gt[i][1]);
		euler_gt[2] = RAD2DEG(test_meas_data_euler_gt[i][2]);

		// calculate rms error
		rms_errors[i] = euler_rms_error(euler_est, euler_gt);
	}

	// check if cum rms error is within some threshold
	float rms_error_mean, rms_error_std;
	mean_std(&rms_error_mean, &rms_error_std, rms_errors, TEST_MEAS_DATA_MEAS_LEN);
	printf("C: rms_error_mean = %f [deg]\n", rms_error_mean);
	printf("C: rms_error_std  = %f [deg]\n", rms_error_std);

	FILE *fptr;
    if ((fptr = fopen("../logs/test_OR_rms_error_results.log", "r")) == NULL){
        printf("Error! opening file ../matlab/tests/test_results.txt\n");
        exit(1);
    }

	float matlab_code_rms_err_mean, matlab_code_rms_err_std;
    fscanf(fptr, "%f\n%f", &matlab_code_rms_err_mean, &matlab_code_rms_err_std);
    fclose(fptr);

	printf("MATLAB: rms_error_mean = %f [deg]\n", matlab_code_rms_err_mean);
	printf("MATLAB: rms_error_std  = %f [deg]\n", matlab_code_rms_err_std);

	float eps = 0.1f; // deg difference between matlab and c code implementation
    mu_assert_float_eps_eq(matlab_code_rms_err_mean, rms_error_mean, eps);
    mu_assert_float_eps_eq(matlab_code_rms_err_std, rms_error_std, eps);
}

MU_TEST_SUITE(test_suite) {
    MU_RUN_TEST(test_compare_matlab_and_c);
}

int main(int argc, char *argv[]) {

	(void)argc;
	(void)argv;
	
	MU_RUN_SUITE(test_suite);
	MU_REPORT();
    
	return MU_EXIT_CODE;
}
