// Generated by {project_root}/matlab/tests/gen_meas_for_c.m script.
// Author: Ivan Vnucec, 2021
// License: MIT

#ifndef TEST_MEAS_DATA_H
#define TEST_MEAS_DATA_H

#define MEAS_LEN (201)

extern float test_meas_data_acc[MEAS_LEN][3];
extern float test_meas_data_mag[MEAS_LEN][3];
extern float test_meas_data_gyr[MEAS_LEN][3];
extern float test_meas_data_euler_gt[MEAS_LEN][3];

#endif // TEST_MEAS_DATA_H
