name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo ./scripts/install_deps.sh

      - name: Run Clang format check
        run: make clang_format_check

      - name: Build project
        run: make build
        
      - name: Run cppcheck
        run: |
          make cppcheck
          cat logs/cppcheck.log

      - name: Test project
        run: make test

      - name: Generate Code coverage report
        run: make codecov

      - name: Generate O.R. static library for ARM Cortex-m4
        run: make cross_build
        
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: |
            cross_builddir/meson-logs
            cross_builddir/src/opt_req/libopt_req_cross.a
            builddir/meson-logs
            logs
      
      - name: Cat meson-log
        run: |
          cat ./builddir/meson-logs/meson-log.txt

      - name: Cat testlog
        if: always()
        run: |
          cat ./builddir/meson-logs/testlog.txt
          
