name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo ./scripts/install_deps.sh

      - name: Run Clang format check
        run: make clang_format_check

      - name: Build project
        run: make build
        
      - name: Run cppcheck
        run: make cppcheck

      - name: Test project
        run: make test

      - name: Generate Code coverage report
        run: make codecov

      - name: Generate Doxygen documentation
        run: make doxygen
        
      - name: Upload Meson logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: meson-logs
          path: ./builddir/meson-logs/

      - name: Upload Doxygen files
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-files
          path: ./docs/Doxygen
        