name: Test Matlab

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install GNU Octave
        id: octave_install
        run: sudo make install_gnu_octave

      # Run tests 10 times because we have randomly generated measurements
      - name: Run tests1
        run: make matlab_test

      - name: Run tests2
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests3
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests4
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests5
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests6
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests7
        if: ${{ success() }}
        run: make matlab_test
      
      - name: Run tests8
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests9
        if: ${{ success() }}
        run: make matlab_test

      - name: Run tests10
        if: ${{ success() }}
        run: make matlab_test

      # Upload a Matlab plot of the failed step
      - name: Upload Matlab plot
        if: ${{ failure() && steps.octave_install.outcome == 'success' }}
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: plot
          path: matlab/tests/*.jpg
