name: Test Matlab

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Install GNU Octave
        id: octave_install
        run: |
          sudo apt-get update
          sudo apt-get install -y octave

      - name: Run tests
        if: ${{ success() }}
        run: make matlab_test

      # Upload a Matlab plot of the failed step
      - name: Upload Matlab plot
        if: ${{ failure() && steps.octave_install.outcome == 'success' }}
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: matlab_plots
          path: matlab/tests/figures
